# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "Docker" ]
  pull_request:
    branches: [ "Docker" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Get timestamp
      id: timestamp
      run: echo "TIMESTAMP=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.0'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Login to DockerHub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: |
        docker build -t mathieuplateforme/mys3:${{ env.TIMESTAMP }} .
        docker push mathieuplateforme/mys3:${{ env.TIMESTAMP }}

  notify-result:
    needs: [build]
    runs-on: ubuntu-latest
    if: always() 
    steps:
    - name: Notify result
      env:
        CHAT_WEBHOOK_URL: ${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}
      run: |
        if [ "${{ needs.build.result }}" == "success" ]; then
          STATUS="Success"
        else
          STATUS="Failure"
        fi
        curl -X POST -H 'Content-Type: application/json' -d "{\"text\": \"Workflow $STATUS: ${{ github.repository }}\"}" $CHAT_WEBHOOK_URL
